In [1]:
import numpy as np

In [63]:
arr1 = np.array([ [3.3, 9.0, 6.0, 3, 6], [4.0, 7, 88, 5.1, 6.2] ], dtype = 'float64') 

In [64]:
print(arr1)

[[ 3.3  9.   6.   3.   6. ]
 [ 4.   7.  88.   5.1  6.2]]


In [65]:
arr1.dtype

dtype('float64')

In [66]:
arr1.shape

(2, 5)

In [67]:
arr1.dtype

dtype('float64')

In [68]:
arr1.ndim

2

In [69]:
arr1.itemsize

8

In [70]:
arr1.nbytes

80

In [71]:
arr1[1, -2]

5.1

In [72]:
arr1[:, 1]

array([9., 7.])

In [73]:
arr1[0, :]

array([3.3, 9. , 6. , 3. , 6. ])

In [78]:
arr1[1, 0: 5: 2]

array([ 4. , 88. ,  6.2])

In [79]:
arr1[1, 2] = 9

In [80]:
arr1

array([[3.3, 9. , 6. , 3. , 6. ],
       [4. , 7. , 9. , 5.1, 6.2]])

In [82]:
arr1[:, 1] = [2, 3]
arr1

array([[3.3, 2. , 6. , 3. , 6. ],
       [4. , 3. , 9. , 5.1, 6.2]])

# 3-d array example

In [95]:
arr2 = np.array([ [ [2, 4, 5], [7, 3, 3], [7, 5, 1] ] , [ [4, 5, 3], [1, 2, 7], [1, 2, 4] ] ])
print(arr2)

[[[2 4 5]
  [7 3 3]
  [7 5 1]]

 [[4 5 3]
  [1 2 7]
  [1 2 4]]]


In [96]:
arr2.dtype

dtype('int32')

In [97]:
arr2.size

18

In [98]:
arr2.shape

(2, 3, 3)

In [99]:
arr2.ndim

3

In [101]:
arr2[0, 2, 1]

5

In [103]:
arr2[:, 1, :]

array([[7, 3, 3],
       [1, 2, 7]])

In [104]:
arr2[1, 0, :] = 6

In [105]:
arr2

array([[[2, 4, 5],
        [7, 3, 3],
        [7, 5, 1]],

       [[6, 6, 6],
        [1, 2, 7],
        [1, 2, 4]]])

# Types of Matrices

In [108]:
#zero matrix
np.zeros((4, 5, 6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [110]:
#Ones matrix
np.ones((3, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [111]:
#Full matrix
np.full((2, 3, 4), 5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [112]:
#FUll-like
np.full_like(arr1, 6)

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [116]:
#Random decimal no.s
np.random.rand(3,5)

array([[0.43301758, 0.30746403, 0.69292695, 0.17114545, 0.70973953],
       [0.79893746, 0.47748418, 0.41040225, 0.17998346, 0.19119432],
       [0.17641117, 0.27480782, 0.6496348 , 0.48827981, 0.16582586]])

In [117]:
np.random.random_sample(arr1.shape)

array([[0.6274527 , 0.5893289 , 0.89102989, 0.53429911, 0.20435672],
       [0.83904172, 0.01879238, 0.04217641, 0.59889522, 0.17588129]])

In [122]:
#Random Integer no.s
np.random.randint(2, size = (3, 3))

array([[1, 0, 1],
       [1, 1, 1],
       [0, 1, 0]])

In [124]:
#Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [132]:
np.repeat([[3, 5, 6, 6], [6, 7, 7, 5]], 4, axis = 0)

array([[3, 5, 6, 6],
       [3, 5, 6, 6],
       [3, 5, 6, 6],
       [3, 5, 6, 6],
       [6, 7, 7, 5],
       [6, 7, 7, 5],
       [6, 7, 7, 5],
       [6, 7, 7, 5]])

# Implementation

![ese_hi](ese_hi.jpg "Task")

In [147]:
arr = np.ones((5,5), dtype = 'int32')
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [158]:
x = np.zeros((3, 3))
x[1, 1] = 9
x

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [160]:
arr[1:-1, 1:-1] = x
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

# XXX Caution when copying arrays!! XXX

In [163]:
a = np.array([[4, 5, 6], [3, 4, 5]])
a

array([[4, 5, 6],
       [3, 4, 5]])

In [164]:
b = a
b[0, 2] = 0
b

array([[4, 5, 0],
       [3, 4, 5]])

In [165]:
a

array([[4, 5, 0],
       [3, 4, 5]])

In [167]:
#to avoid, do this: 
x = np.array([ [4, 5, 5], [6, 3, 6] ])
y = x.copy()
y[0, 2] = 10
y

array([[ 4,  5, 10],
       [ 6,  3,  6]])

In [168]:
x

array([[4, 5, 5],
       [6, 3, 6]])

# Mathematics

In [169]:
a = np.array([3, 4, 5, 6])

In [177]:
b = np.array([3, 5, 3, 1])
a ** b

array([  27, 1024,  125,    6])

In [178]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [179]:
np.sin(b)

array([ 0.14112001, -0.95892427,  0.14112001,  0.84147098])

In [180]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

# Linear Algebra

In [181]:
#Matrix multiplication
a = np.array([ [3, 4, 5], [3, 6, 7] ])    #shape = (2, 3)
b = np.array([ [5, 6], [4, 7], [2, 7] ])    #shape = (3, 2)
np.matmul(a, b)    #shape = (2, 2)

array([[ 41,  81],
       [ 53, 109]])

In [195]:
#Determinant of matrix
a = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ], dtype = 'int32')
b = np.array([ [10, 11], [13, 14] ], dtype = 'int32')
print("Det a: ", round(np.linalg.det(a), 3))
print("Det b: ", round(np.linalg.det(b), 3))

Det a:  -0.0
Det b:  -3.0


In [197]:
np.linalg.svd(a)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [198]:
np.linalg.eigvals(a)

array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16])

In [199]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

# Statistics

In [210]:
a

array([[1, 4, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [211]:
np.min(a)

1

In [212]:
np.max(a)

9

In [213]:
np.min(a, axis = 0)

array([1, 4, 3])

In [214]:
np.max(a, axis = 1)

array([4, 6, 9])

In [217]:
np.sum(a, axis = 0)

array([12, 17, 18])

# Reorganizing arrays

In [225]:
#Reshaping
a = np.array([ [4, 3, 2], [5, 6, 7] ])
a.shape

(2, 3)

In [229]:
a.reshape((3, 2))

array([[4, 3],
       [2, 5],
       [6, 7]])

In [223]:
a

array([[1, 4, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [232]:
#Vertical stacking
a = np.array([ [4, 5, 10], [6, 7, 8] ])
b = np.array([ [6, 7, 11], [8, 9, 10] ])
np.vstack([ a, b, b, a ])

array([[ 4,  5, 10],
       [ 6,  7,  8],
       [ 6,  7, 11],
       [ 8,  9, 10],
       [ 6,  7, 11],
       [ 8,  9, 10],
       [ 4,  5, 10],
       [ 6,  7,  8]])

In [234]:
np.hstack([ a, b , a, b])

array([[ 4,  5, 10,  6,  7, 11,  4,  5, 10,  6,  7, 11],
       [ 6,  7,  8,  8,  9, 10,  6,  7,  8,  8,  9, 10]])

# Miscellaneous 

### Loading data from file

In [243]:
filedata = np.genfromtxt('num_file.txt', delimiter = ', ')
filedata = filedata.astype('int32')
filedata

array([[  4,   5,   6,   7,   8,   8,   9,  10,  11],
       [  2,   6,   3,   7,   3,   8,   2,   4,   3],
       [  1,   4,   6,   2,  44,  66,  22,  66,  22],
       [  2,   4,   6,   8,   2,   5,  45,  35, 356],
       [  4,   6,   7,   8,   9,  34,  67,  23,  78]])

### Boolean Masking and Advanced Indexing

In [244]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False],
       [False, False, False, False, False, False, False, False,  True],
       [False, False, False, False, False, False,  True, False,  True]])

In [245]:
filedata[filedata > 50]

array([ 66,  66, 356,  67,  78])

In [255]:
# You can index with a list in NumPy
a = np.array([1, 2, 3, 45, 6, 7, 8, 8, 5, 20])
a[[4, 5, 6]]

array([6, 7, 8])

In [258]:
print(filedata)
np.any(filedata > 50, axis = 0)

[[  4   5   6   7   8   8   9  10  11]
 [  2   6   3   7   3   8   2   4   3]
 [  1   4   6   2  44  66  22  66  22]
 [  2   4   6   8   2   5  45  35 356]
 [  4   6   7   8   9  34  67  23  78]]


array([False, False, False, False, False,  True,  True,  True,  True])

In [262]:
np.all(filedata > 2, axis = 1)

array([ True, False, False, False,  True])

In [268]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False,  True]])

In [269]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True, False]])

![test2](test2.jpg "Task")

In [272]:
test2 = np.array([ [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14 , 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30] ])
test2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [300]:
test2[2:4, 0:2]

array([[11, 12],
       [16, 17]])

![test3](test3.jpg "Task")

In [316]:
test2[ [0, 1, 2, 3], [1, 2, 3, 4] ]

array([ 2,  8, 14, 20])

![test4](test4.jpg "Task")

In [322]:
np.vstack([ test2[0, 3:5], test2[4:6, 3:5] ])

array([[ 4,  5],
       [24, 25],
       [29, 30]])

## or

In [323]:
test2[ [0, 4, 5], 3: ]

array([[ 4,  5],
       [24, 25],
       [29, 30]])